"""empty message

Revision ID: 903bb061b48d
Revises: 
Create Date: 2022-01-26 08:19:27.966280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '903bb061b48d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('places')
    # ### end Alembic commands ###
